. (Join-Path $PSScriptRoot 'assert.ps1')
. (Join-Path $PSScriptRoot 'common.ps1')

function New-ToolingFixture {
    $root = Join-Path (Get-RepoRoot) ('.tooling-fixture-' + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $root | Out-Null
    foreach ($folder in @('infra', 'scripts', 'tests', 'docs')) {
        Copy-Item -LiteralPath (Get-RepoPath $folder) -Destination $root -Recurse -Force
    }
    Copy-Item -LiteralPath (Get-RepoPath 'azure.yaml') -Destination $root
    $instructions = Join-Path $root '.github/instructions'
    New-Item -ItemType Directory -Path $instructions -Force | Out-Null
    Copy-Item -LiteralPath (Get-RepoPath '.github/instructions/naming.instructions.md') -Destination $instructions
    return $root
}

function Get-FixtureSnapshot {
    param([string] $Root)
    $paths = @('infra/modules/bastion', 'infra/modules/catalog.json', 'infra/core/private-dns-zones.json', 'docs/modules.md', 'unrelated.txt')
    $snapshot = foreach ($relative in $paths) {
        Get-ChildItem -LiteralPath (Join-Path $Root $relative) -File -Recurse -Force | Sort-Object FullName | ForEach-Object {
            "$($_.FullName.Substring($Root.Length))=$((Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash)"
        }
    }
    return $snapshot -join "`n"
}

foreach ($failure in @('metadata', 'conformance', 'publication')) {
    Test-Case "forced promotion preserves original files, generated bytes and index after $failure failure" {
        $root = New-ToolingFixture
        try {
            $source = Join-Path $root 'source'
            Copy-Item -LiteralPath (Join-Path $root 'infra/modules/bastion') -Destination $source -Recurse
            $metadataPath = Join-Path $source 'metadata.json'
            $metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json -AsHashtable
            if ($failure -eq 'metadata') { $metadata.preflight.Remove('checks') }
            if ($failure -eq 'conformance') { $metadata.abbreviation = 'unapproved' }
            $metadata | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $metadataPath
            Add-Content -LiteralPath (Join-Path $source 'README.md') -Value 'Candidate revision.'
            Set-Content -LiteralPath (Join-Path $root 'unrelated.txt') -Value 'staged baseline'
            & git -C $root init --quiet
            if ($LASTEXITCODE -ne 0) { throw 'Unable to initialize disposable fixture index.' }
            & git -C $root add -- unrelated.txt infra/modules/bastion docs/modules.md
            if ($LASTEXITCODE -ne 0) { throw 'Unable to stage disposable fixture baseline.' }
            Add-Content -LiteralPath (Join-Path $root 'unrelated.txt') -Value 'unstaged change'
            [IO.File]::WriteAllBytes((Join-Path $root 'infra/modules/bastion/.local.bin'), [byte[]] @(0, 255, 13, 10, 128))
            Add-Content -LiteralPath (Join-Path $root 'infra/modules/bastion/README.md') -Value 'Uncommitted original.'
            Add-Content -LiteralPath (Join-Path $root 'docs/modules.md') -Value 'Uncommitted doc notes.'
            $snapshot = Get-FixtureSnapshot $root
            $indexHash = (Get-FileHash -LiteralPath (Join-Path $root '.git/index')).Hash
            $message = ''
            if ($failure -eq 'publication') {
                function git { $global:LASTEXITCODE = 1 }
            }
            try {
                & (Join-Path $root 'scripts/promote-module.ps1') -From $source -Name bastion -Force | Out-Null
            }
            catch { $message = $_.Exception.Message }
            finally {
                if ($failure -eq 'publication') { Remove-Item Function:\git }
            }
            $expected = switch ($failure) {
                metadata { 'preflight requires' }
                conformance { 'test case\(s\) failed' }
                publication { 'Unable to stage promotion' }
            }
            Assert-Match -Actual $message -Pattern $expected -Message 'The intended gate must fail.'
            Assert-Equal -Actual (Get-FixtureSnapshot $root) -Expected $snapshot -Message 'All original bytes, including untracked files, must survive.'
            Assert-Equal -Actual (Get-FileHash -LiteralPath (Join-Path $root '.git/index')).Hash -Expected $indexHash -Message 'Existing staged state must survive.'
            Assert-Equal -Actual @(Get-ChildItem -LiteralPath $root -Filter '.promotion-*' -Force).Count -Expected 0 -Message 'Promotion scratch must be cleaned.'
        }
        finally { Remove-Item -LiteralPath $root -Recurse -Force }
    }
}

function New-IdentityModule {
    param([string] $Root)
    $abbreviationsPath = Join-Path $Root 'infra/core/abbreviations.json'
    $abbreviations = Get-Content -LiteralPath $abbreviationsPath -Raw | ConvertFrom-Json -AsHashtable
    $abbreviations['userAssignedIdentity'] = 'uai'
    $abbreviations | ConvertTo-Json | Set-Content -LiteralPath $abbreviationsPath
    & (Join-Path $Root 'scripts/new-module.ps1') -Name test-identity -Abbreviation uai `
        -Provider Microsoft.ManagedIdentity -ResourceType Microsoft.ManagedIdentity/userAssignedIdentities `
        -ApiVersion 2023-01-31 -Description 'Disposable identity conformance fixture.' | Out-Null
    $modulePath = Join-Path $Root 'infra/modules/test-identity'
    foreach ($file in @('main.bicep', 'README.md')) {
        $path = Join-Path $modulePath $file
        $text = (Get-Content -LiteralPath $path -Raw).Replace('TODO:', 'Implemented:')
        if ($file -eq 'main.bicep') { $text = $text -replace '(?m)^  properties: \{\r?\n  \}\r?\n', '' }
        $text | Set-Content -LiteralPath $path
    }
    return $modulePath
}

Test-Case 'a real new conforming promotion succeeds and stages fresh catalog, DNS and docs' {
    $root = New-ToolingFixture
    try {
        $modulePath = New-IdentityModule $root
        $source = Join-Path $root 'source'
        Move-Item -LiteralPath $modulePath -Destination $source
        & (Join-Path $root 'scripts/build-catalog.ps1') | Out-Null
        & (Join-Path $root 'scripts/build-docs.ps1') | Out-Null
        & git -C $root init --quiet
        if ($LASTEXITCODE -ne 0) { throw 'Unable to initialize disposable fixture.' }
        Set-Content -LiteralPath (Join-Path $root 'unrelated.txt') -Value 'staged'
        & git -C $root add -- unrelated.txt
        $before = & git -C $root ls-files --stage -- unrelated.txt
        Add-Content -LiteralPath (Join-Path $root 'unrelated.txt') -Value 'unstaged'
        $result = & (Join-Path $root 'scripts/promote-module.ps1') -From $source -Name test-identity
        Assert-Equal -Actual $result.Action -Expected 'Promoted' -Message 'Happy-path promotion must succeed.'
        Assert-True -Condition $result.TestsPassed -Message 'Real conformance suite must pass.'
        Assert-True -Condition $result.Staged -Message 'Successful promotion must stage changes.'
        & (Join-Path $root 'scripts/build-catalog.ps1') -Check
        & (Join-Path $root 'scripts/build-docs.ps1') -Check
        $staged = @(& git -C $root diff --cached --name-only)
        foreach ($path in @('infra/modules/test-identity/main.bicep', 'infra/modules/test-identity/metadata.json', 'infra/modules/test-identity/README.md', 'infra/modules/catalog.json', 'infra/core/private-dns-zones.json', 'docs/modules.md')) {
            Assert-True -Condition ($path -in $staged) -Message "Expected staged artifact '$path'."
        }
        Assert-Equal -Actual (& git -C $root ls-files --stage -- unrelated.txt) -Expected $before -Message 'Unrelated staged entry must not change.'
        Assert-Match -Actual (Get-Content -LiteralPath (Join-Path $root 'unrelated.txt') -Raw) -Pattern 'unstaged' -Message 'Unrelated working tree must not change.'
    }
    finally { Remove-Item -LiteralPath $root -Recurse -Force }
}

foreach ($moduleName in @('bastion', 'jumpboxes', 'key-vault', 'monitoring', 'nat-gateway', 'network', 'private-dns', 'storage')) {
    Test-Case "add-module explicitly rejects incomplete $moduleName wiring before any edits" {
        $root = New-ToolingFixture
        try {
            $main = Join-Path $root 'infra/main.bicep'
            Set-Content -LiteralPath $main -Value "// #region modules`n// #endregion modules"
            $before = (Get-FileHash -LiteralPath $main).Hash
            $message = ''
            try { & (Join-Path $root 'scripts/add-module.ps1') -Module $moduleName | Out-Null }
            catch { $message = $_.Exception.Message }
            Assert-Match -Actual $message -Pattern 'Required inputs needing explicit bindings: \[.+' -Message 'Rejection must explain missing input bindings.'
            Assert-Match -Actual $message -Pattern 'no files were changed' -Message 'Rejection must be actionable.'
            Assert-Equal -Actual (Get-FileHash -LiteralPath $main).Hash -Expected $before -Message 'Rejected wiring must not edit main.'
        }
        finally { Remove-Item -LiteralPath $root -Recurse -Force }
    }
}

Test-Case 'new-module to add-module completed snippet compiles and repeat wiring is a no-op' {
    $root = New-ToolingFixture
    try {
        $null = New-IdentityModule $root
        $main = Join-Path $root 'infra/main.bicep'
        $preamble = @'
targetScope = 'subscription'
import { azName, abbreviations } from './core/naming.bicep'
param location string = 'eastus'
var locationCode = 'eus'
var subscriptionCode = 's1'
var environmentName = 'test'
var tags = {}
var featureSettings = { testIdentity: false }
resource resourceGroup 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: 'rg-fixture'
  location: location
}
// #region modules
// #endregion modules
'@
        Set-Content -LiteralPath $main -Value $preamble
        $result = @(& (Join-Path $root 'scripts/add-module.ps1') -Module test-identity)[-1]
        Assert-Equal -Actual $result.Action -Expected 'Inserted' -Message 'Supported scaffold wiring must succeed.'
        $complete = ($preamble -replace "`r`n", "`n").Replace("// #region modules`n// #endregion modules", $result.Snippet)
        Assert-Match -Actual $complete -Pattern 'module testIdentity' -Message 'The compiled fixture must actually contain the generated module.'
        [IO.File]::WriteAllText($main, $complete)
        & az bicep build --file $main --stdout | Out-Null
        Assert-Equal -Actual $LASTEXITCODE -Expected 0 -Message 'Completed generated wiring must compile.'
        $before = (Get-FileHash -LiteralPath $main).Hash
        $again = & (Join-Path $root 'scripts/add-module.ps1') -Module test-identity
        Assert-Equal -Actual $again.Action -Expected 'AlreadyPresent' -Message 'Repeat wiring must be idempotent.'
        Assert-Equal -Actual (Get-FileHash -LiteralPath $main).Hash -Expected $before -Message 'Repeat wiring must not edit.'
    }
    finally { Remove-Item -LiteralPath $root -Recurse -Force }
}

foreach ($profile in @('', 'private', 'minimal', 'full')) {
    Test-Case "adopted hook executes copied dependencies with azd profile '$profile'" {
        $root = New-ToolingFixture
        try {
            $target = Join-Path $root 'adopted'
            New-Item -ItemType Directory -Path (Join-Path $target 'infra/modules') -Force | Out-Null
            Copy-Item -LiteralPath (Join-Path $root 'infra/modules/catalog.json') -Destination (Join-Path $target 'infra/modules/catalog.json')
            $output = @(& (Join-Path $root 'scripts/adopt-conventions.ps1') -Path $target)
            $hook = @($output | Where-Object { $_ -is [string] -and $_.StartsWith('hooks:') })[0]
            $body = ($hook -split "`n" | Where-Object { $_ -match '^      ' } | ForEach-Object { $_.Substring(6) }) -join "`n"
            $values = @{
                DEPLOYMENT_PROFILE = $profile; AZURE_REPOSITORY = 'fixture'
                AZURE_SUBSCRIPTION_ID = '11111111-1111-1111-1111-111111111111'
                AZURE_SUBSCRIPTION_CODE = 's1'; AZURE_LOCATION = 'eastus'; AZURE_ENV_NAME = 'fixture'
                AZURE_FEATURE_OVERRIDES_JSON = '{}'; AZURE_OPERATOR_PRINCIPAL_IDS = ''
            }
            if ($profile -eq 'full') { $values.AZURE_OPERATOR_PRINCIPAL_IDS = '22222222-2222-2222-2222-222222222222' }
            function azd {
                $global:LASTEXITCODE = 0
                if ($args[0] -ne 'env') { throw "Unexpected azd call: $args" }
                if ($args[1] -eq 'set') { $values[$args[2]] = [string] $args[3]; return }
                if ($args[1] -eq 'get-value') {
                    if ($values.ContainsKey($args[2])) { return $values[$args[2]] }
                    $global:LASTEXITCODE = 1
                    return
                }
                throw "Unexpected azd call: $args"
            }
            function az {
                $global:LASTEXITCODE = 0
                switch ("$($args[0]) $($args[1])") {
                    'account show' {
                        if ($args -contains 'tsv') { return 'fixture-1' }
                        return '{"name":"fixture-1","state":"Enabled"}'
                    }
                    'account list-locations' { return '["eastus"]' }
                    'provider show' { return 'Registered' }
                    'vm list-skus' { return '[{"restrictions":[]}]' }
                    'vm image' { return '{}' }
                    'vm list-usage' { return '[{"localName":"Total Regional vCPUs","limit":100,"currentValue":0}]' }
                    default { throw "Unexpected Azure call: $args" }
                }
            }
            Push-Location $target
            try { $execution = (& ([scriptblock]::Create($body))) -join "`n" }
            catch { throw "$($_.Exception.Message)`n$($_.ScriptStackTrace)" }
            finally { Pop-Location }
            $expected = if (-not $profile) { 'core' } elseif ($profile -eq 'minimal') { 'private' } else { $profile }
            Assert-Match -Actual $execution -Pattern "using profile '$expected'" -Message 'Real copied scripts must resolve the persisted profile.'
            Assert-Equal -Actual $values.DEPLOYMENT_PROFILE -Expected $(if ($profile) { $profile } else { 'core' }) -Message 'Only missing profile may be initialized.'
        }
        finally { Remove-Item -LiteralPath $root -Recurse -Force }
    }
}

Test-Case 'adoption without a project catalog fails before copying files' {
    $root = New-ToolingFixture
    try {
        $target = Join-Path $root 'empty-target'
        New-Item -ItemType Directory -Path $target | Out-Null
        Assert-Throws -Action { & (Join-Path $root 'scripts/adopt-conventions.ps1') -Path $target } -Message 'Missing runtime catalog must not be silently accepted.'
        Assert-Equal -Actual @(Get-ChildItem -LiteralPath $target -Force).Count -Expected 0 -Message 'Rejected adoption must not write.'
    }
    finally { Remove-Item -LiteralPath $root -Recurse -Force }
}

Test-Case 'compiled template accepts stdout JSON and preserves stderr warnings' {
    $script:CompiledTemplates = @{}
    function az {
        & pwsh -NoProfile -Command '[Console]::Out.WriteLine(''{"resources":{}}''); [Console]::Error.WriteLine(''upgrade available''); exit 0'
        $global:LASTEXITCODE = $LASTEXITCODE
    }
    $warnings = @()
    $template = Get-CompiledTemplate -BicepPath (Get-RepoPath 'infra/main.bicep') -WarningVariable warnings -WarningAction SilentlyContinue
    Assert-True -Condition ($null -ne $template.resources) -Message 'Successful stdout must parse as JSON.'
    Assert-Match -Actual ($warnings -join "`n") -Pattern 'upgrade available' -Message 'Compiler diagnostics must be preserved.'
    $script:CompiledTemplates = @{}
}

Test-Case 'compiled template fails nonzero compilation and preserves diagnostics' {
    $script:CompiledTemplates = @{}
    function az {
        & pwsh -NoProfile -Command '[Console]::Out.WriteLine(''{"resources":{}}''); [Console]::Error.WriteLine(''compiler fixture failure''); exit 7'
        $global:LASTEXITCODE = $LASTEXITCODE
    }
    $message = ''
    try { Get-CompiledTemplate -BicepPath (Get-RepoPath 'infra/main.bicep') | Out-Null }
    catch { $message = $_.Exception.Message }
    Assert-Match -Actual $message -Pattern 'exit 7' -Message 'Nonzero exit must fail even with valid stdout JSON.'
    Assert-Match -Actual $message -Pattern 'compiler fixture failure' -Message 'Failure diagnostics must be preserved.'
    Assert-Equal -Actual $script:CompiledTemplates.Count -Expected 0 -Message 'Failed compilation must not be cached.'
}
